feat(jenkins): rotate jenkins ssh certificates

diff --git a/ansible/roles/jenkins/templates/sign-jenkins-ssh-cert.sh.j2 b/ansible/roles/jenkins/templates/sign-jenkins-ssh-cert.sh.j2
--- a/ansible/roles/jenkins/templates/sign-jenkins-ssh-cert.sh.j2
+++ b/ansible/roles/jenkins/templates/sign-jenkins-ssh-cert.sh.j2
@@ -1,28 +1,54 @@
-#!/bin/sh
+#!/bin/bash
+
+# Author: Dzintars Klavins
+
+# This script authenticates against Vault and signs the Jenkins user SSH
+# certificate. Most likely it is triggered by Systemd timer unit.
+
 set -eu -o pipefail
 
-token_path=/root/.vault-token
-vault_addr=https://vault.{{ root_domain }}
-ssh_pub_key_path=/var/lib/jenkins/.ssh/id_ecdsa_key.pub
-ssh_cert_path=/var/lib/jenkins/.ssh/id_ecdsa_key-cert.pub
+VAULT_ADDR='https://vault.{{ root_domain }}'
+ROLE_ID="{{ jenkins_approle_role_id }}"
+SECRET_ID="{{ jenkins_approle_secret_id }}"
+SSH_PUB_KEY_PATH='/var/lib/jenkins/.ssh/id_ecdsa.pub'
+SSH_CERT_PATH='/var/lib/jenkins/.ssh/id_ecdsa-cert.pub'
 
-curl -sS \
-  -X POST \
-  -d @- "$vault_addr/v1/auth/approle/login" <<-EOF | jq -r '.auth.client_token' > $token_path
-{
-"role_id": "{{ jenkins_approle_role_id }}",
-"secret_id": "{{ jenkins_approle_secret_id }}"
+main () {
+  local VAULT_TOKEN=$(vault_signin "${ROLE_ID}" "${SECRET_ID}")
+  local SSH_PUB_KEY=$(cat "${SSH_PUB_KEY_PATH}")
+
+  sign_ssh_cert "${VAULT_TOKEN}" "${SSH_PUB_KEY}" "${SSH_CERT_PATH}"
+
+  chmod 0640 ${SSH_CERT_PATH}
 }
-EOF
 
-curl -sS \
-  -H "X-Vault-Token: $(cat $token_path)" \
-  -X POST \
-  -d @- "$vault_addr/v1/ssh-client-signer/sign/clientrole" <<-EOF | jq -r .data.signed_key > $ssh_cert_path
-{
-  "public_key": "$(cat $ssh_pub_key_path)",
-  "cert_type": "user"
+vault_signin () {
+  local ROLE_ID=$1
+  local SECRET_ID=$2
+
+  local RES=$(curl -s --request POST \
+    --data '{"role_id": "'"${ROLE_ID}"'", "secret_id": "'"${SECRET_ID}"'"}' \
+    ${VAULT_ADDR}/v1/auth/approle/login | jq -r .auth.client_token)
+
+  local RT=$?
+  if [ "$RT" == "0" ]; then
+    echo $RES
+  else
+    echo "Login with role $ROLE_ID failed. RT:$RT $RES"
+    echo ""
+  fi
 }
-EOF
-chmod 0640 $ssh_cert_path
 
+sign_ssh_cert () {
+  local VAULT_TOKEN="$1";
+  local PUB_KEY="$2";
+  local CERT_PATH="$3";
+
+  curl -s \
+    --header "X-Vault-Token: ${VAULT_TOKEN}" \
+    --request POST \
+    --data '{"public_key": "'"${PUB_KEY}"'", "cert_type": "user"}' \
+    ${VAULT_ADDR}/v1/ssh-client-signer/sign/clientrole | jq -r .data.signed_key > "${CERT_PATH}"
+}
+
+main "$@"; exit
